apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: {{ .Release.Namespace }}
  labels:
    app: rest
spec:
  type: {{ .Values.rest.service.type }}
  selector:
    app: rest
  ports:
    - port: 8080
      name: https
      targetPort: 8080
      protocol: TCP
      {{- if eq .Values.rest.service.type "NodePort" }}
      nodePort: {{ .Values.rest.service.nodePort.https }}
      {{- end }}
    - port: 8081
      name: http
      targetPort: 8081
      protocol: TCP
      {{- if eq .Values.rest.service.type "NodePort" }}
      nodePort: {{ .Values.rest.service.nodePort.http }}
      {{- end }}
