name: "Release Artifacts"
on:
  push:
    branches:
      - master
      - 'release/**'
      - 'hotfix-v**'

jobs:
  kubectl-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
    - uses: cachix/install-nix-action@5f45af07a1f451c75a4ce84e1514200195a1f279 # v15
      with:
        nix_path: nixpkgs=channel:nixos
    - run: nix-build -A utils.release.linux-musl.kubectl-plugin
    - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
      with:
        name: kubectl-mayastor
        path: ./result/bin/kubectl-mayastor
    - run: nix-build -A utils.release.windows-gnu.kubectl-plugin
    - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
      with:
        name: kubectl-mayastor.exe
        path: ./result/bin/kubectl-mayastor.exe
